#pragma once

#include "incbin.h"

INCBIN_EXTERN(MainFont);
INCBIN_EXTERN(Ost00);
INCBIN_EXTERN(Ost01);
INCBIN_EXTERN(Ost02);
INCBIN_EXTERN(Ost03);
INCBIN_EXTERN(Ost04);
INCBIN_EXTERN(Ost05);
INCBIN_EXTERN(Ost06);
INCBIN_EXTERN(Ost07);
INCBIN_EXTERN(Ost08);
INCBIN_EXTERN(Ost09);
INCBIN_EXTERN(Ost10);
INCBIN_EXTERN(Ost11);
INCBIN_EXTERN(Ost12);
INCBIN_EXTERN(Ost13);
INCBIN_EXTERN(Ost14);
INCBIN_EXTERN(Ost15);
INCBIN_EXTERN(Ost16);
INCBIN_EXTERN(Ost17);
INCBIN_EXTERN(Ost18);
INCBIN_EXTERN(Ost19);